import { deepFreeze } from '../contracts/brandUniverseContract.js';

export const VISUAL_BINDING_VERSION = 'ACTIVE_THEORY_V2_BINDING_1.0';

export const BINDING_CHANNEL = deepFreeze({
  HOME_GEO_DENSITY: 'HOME_GEO_DENSITY',
  HOME_GEO_ENERGY: 'HOME_GEO_ENERGY',
  HOME_GEO_ACTIVITY: 'HOME_GEO_ACTIVITY',
  HOME_GEO_EMPHASIS: 'HOME_GEO_EMPHASIS',
  HOME_FIVE_A_DENSITY: 'HOME_FIVE_A_DENSITY',
  HOME_FIVE_A_ENERGY: 'HOME_FIVE_A_ENERGY',
  HOME_FIVE_A_ACTIVITY: 'HOME_FIVE_A_ACTIVITY',
  HOME_FIVE_A_EMPHASIS: 'HOME_FIVE_A_EMPHASIS',
  HOME_BRAND_MIND_DENSITY: 'HOME_BRAND_MIND_DENSITY',
  HOME_BRAND_MIND_ENERGY: 'HOME_BRAND_MIND_ENERGY',
  HOME_BRAND_MIND_ACTIVITY: 'HOME_BRAND_MIND_ACTIVITY',
  HOME_BRAND_MIND_EMPHASIS: 'HOME_BRAND_MIND_EMPHASIS',

  GEO_ANSWER_DENSITY: 'GEO_ANSWER_DENSITY',
  GEO_ANSWER_ENERGY: 'GEO_ANSWER_ENERGY',
  GEO_ANSWER_FLOW_SPEED: 'GEO_ANSWER_FLOW_SPEED',
  GEO_ANSWER_HIGHLIGHT_RATE: 'GEO_ANSWER_HIGHLIGHT_RATE',
  GEO_CITATION_DENSITY: 'GEO_CITATION_DENSITY',
  GEO_CITATION_ENERGY: 'GEO_CITATION_ENERGY',
  GEO_CITATION_FLOW_SPEED: 'GEO_CITATION_FLOW_SPEED',
  GEO_CITATION_HIGHLIGHT_RATE: 'GEO_CITATION_HIGHLIGHT_RATE',
  GEO_KEYWORD_DENSITY: 'GEO_KEYWORD_DENSITY',
  GEO_KEYWORD_ENERGY: 'GEO_KEYWORD_ENERGY',
  GEO_KEYWORD_FLOW_SPEED: 'GEO_KEYWORD_FLOW_SPEED',
  GEO_KEYWORD_HIGHLIGHT_RATE: 'GEO_KEYWORD_HIGHLIGHT_RATE',
  GEO_SIGNAL_CORE_DENSITY: 'GEO_SIGNAL_CORE_DENSITY',
  GEO_SIGNAL_CORE_ENERGY: 'GEO_SIGNAL_CORE_ENERGY',
  GEO_SIGNAL_CORE_HIGHLIGHT_RATE: 'GEO_SIGNAL_CORE_HIGHLIGHT_RATE',
  GEO_SIGNAL_CORE_CONFIDENCE: 'GEO_SIGNAL_CORE_CONFIDENCE',

  FIVEA_STAGE_SCALE: 'FIVEA_STAGE_SCALE',
  FIVEA_STAGE_DENSITY: 'FIVEA_STAGE_DENSITY',
  FIVEA_STAGE_ENERGY: 'FIVEA_STAGE_ENERGY',
  FIVEA_STAGE_ACTIVITY: 'FIVEA_STAGE_ACTIVITY',
  FIVEA_TRANSITION_FLOW_STRENGTH: 'FIVEA_TRANSITION_FLOW_STRENGTH',
  FIVEA_TRANSITION_FLOW_SPEED: 'FIVEA_TRANSITION_FLOW_SPEED',
  FIVEA_OPPORTUNITY_DENSITY: 'FIVEA_OPPORTUNITY_DENSITY',
  FIVEA_OPPORTUNITY_ENERGY: 'FIVEA_OPPORTUNITY_ENERGY',
  FIVEA_OPPORTUNITY_ACTIVITY: 'FIVEA_OPPORTUNITY_ACTIVITY',

  BRAND_MIND_CORE_DENSITY: 'BRAND_MIND_CORE_DENSITY',
  BRAND_MIND_CORE_ENERGY: 'BRAND_MIND_CORE_ENERGY',
  BRAND_MIND_CORE_CONCENTRATION: 'BRAND_MIND_CORE_CONCENTRATION',
  BRAND_MIND_NODE_SCALE: 'BRAND_MIND_NODE_SCALE',
  BRAND_MIND_NODE_BRIGHTNESS: 'BRAND_MIND_NODE_BRIGHTNESS',
  BRAND_MIND_NODE_ACTIVITY: 'BRAND_MIND_NODE_ACTIVITY',
  BRAND_MIND_NODE_RELATIONSHIP_STRENGTH: 'BRAND_MIND_NODE_RELATIONSHIP_STRENGTH',
  BRAND_MIND_PATH_VISIBILITY: 'BRAND_MIND_PATH_VISIBILITY',
  BRAND_MIND_PATH_FLOW_STRENGTH: 'BRAND_MIND_PATH_FLOW_STRENGTH'
});

export const BINDING_CHANNELS = deepFreeze(Object.values(BINDING_CHANNEL));

export const BINDING_CHANNEL_GROUPS = deepFreeze({
  home: BINDING_CHANNELS.filter((channel) => channel.startsWith('HOME_')),
  geo: BINDING_CHANNELS.filter((channel) => channel.startsWith('GEO_')),
  fiveA: BINDING_CHANNELS.filter((channel) => channel.startsWith('FIVEA_')),
  brandMind: BINDING_CHANNELS.filter((channel) => channel.startsWith('BRAND_MIND_'))
});
