import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { createFiveAScene } from '../../scenes/fiveAScene.js';
import { createFiveAStageRendererAdapter } from './fiveAStageRendererAdapter.js';
import { createFiveAFlowRendererAdapter } from './fiveAFlowRendererAdapter.js';
import { createFiveAFlowDemoSnapshot, resolveFiveAFlowDemo } from '../runtime/fiveAFlowDemo.js';
import { CANONICAL_FIVE_A_MOCK } from '../mock/canonicalFixtures.js';
import { createV2ConsumerProvider } from '../runtime/consumerProvider.js';
import { buildVisualBindingPlan } from '../binding/bindingPlanner.js';
import { buildFiveADataPanelViewModel } from '../../ui/fiveA-data-panel/fiveADataPanelViewModel.js';
globalThis.window = {location:{search:''}};
globalThis.document = {createElement:()=>({getContext:()=>({clearRect(){},fillText(){}})})};
const results=[];
function test(name,run){try{run();results.push({name,status:'pass'});}catch(e){results.push({name,status:'fail',error:e.stack});}}
function pipeline(state){const consumer=createV2ConsumerProvider({fiveASnapshot:createFiveAFlowDemoSnapshot(state)}).getFiveA();const visual=consumer.buildVisualState();return {consumer,visual,plan:buildVisualBindingPlan(visual),panel:buildFiveADataPanelViewModel(consumer.snapshot,consumer.derivedMetrics)};}
const cases=Object.fromEntries(['low','baseline','high','partial'].map(s=>[s,pipeline(s)]));
const scene=createFiveAScene();const stageAdapter=createFiveAStageRendererAdapter(scene.resolveStageRendererTarget);const adapter=createFiveAFlowRendererAdapter(scene.resolveTransitionRendererTarget);
const flow=scene.group.getObjectByName('FiveACoreReleaseParticleFlow');
const tick=(time=12,progress=1)=>scene.update({cameraOffset:{x:0,y:0,z:0,targetY:0}},0,time,progress);
tick();const original=scene.readTransitionRendererStates();
stageAdapter.apply(cases.baseline.plan);tick();const stageOriginal=stageAdapter.getReport().renderer;
const resource={geometry:flow.geometry.uuid,material:flow.material.uuid,count:flow.geometry.attributes.position.count,vertex:flow.material.vertexShader,fragment:flow.material.fragmentShader};
const positions=[...flow.geometry.attributes.position.array];
const evidence={};
for(const [state,run] of Object.entries(cases)){
  adapter.apply(run.plan);tick();evidence[state]={snapshotId:run.consumer.snapshot.metadata.snapshotId,canonical:run.consumer.snapshot.fiveA.transitions.A2_TO_A3,panel:run.panel.transitionRows.find(r=>r.transitionId==='A2_TO_A3'),visual:run.visual.fiveA.transitions.A2_TO_A3,execution:adapter.getReport()};
}
test('stable A2_TO_A3 resolves correct endpoints, not index lookup',()=>{const t=scene.resolveTransitionRendererTarget('A2_TO_A3');assert.equal(t.transitionId,'A2_TO_A3');assert.equal(t.read().sourceId,'A2');assert.equal(t.read().targetId,'A3');assert.equal(scene.resolveTransitionRendererTarget('A1_TO_A2'),null);assert.equal(scene.resolveTransitionRendererTarget(3),null);});
test('four scenarios preserve stages, other transitions and Opportunity facts',()=>{for(const run of Object.values(cases)){const s=run.consumer.snapshot;assert.deepEqual(s.fiveA.stages,CANONICAL_FIVE_A_MOCK.fiveA.stages);assert.deepEqual(s.fiveA.opportunityPool,CANONICAL_FIVE_A_MOCK.fiveA.opportunityPool);for(const id of ['A1_TO_A2','A3_TO_A4','A4_TO_A5'])assert.deepEqual(s.fiveA.transitions[id],CANONICAL_FIVE_A_MOCK.fiveA.transitions[id]);}});
test('synthetic tracked cohort rate equals observed exits / entrants, independent of stage populations',()=>{for(const name of ['low','baseline','high']){const t=evidence[name].canonical;assert.equal(t.rate.value,t.out.value/t.in.value);assert.equal(t.volume.value,t.out.value);assert.equal(t.strength.value,null);assert.notEqual(t.rate.value,CANONICAL_FIVE_A_MOCK.fiveA.stages.A3.population.value/CANONICAL_FIVE_A_MOCK.fiveA.stages.A2.population.value);}});
test('MOCK identity, SYNTHETIC lineage and missing history retained',()=>{for(const run of Object.values(cases)){assert.equal(run.consumer.snapshot.metadata.sourceType,'MOCK');assert.equal(run.consumer.snapshot.metadata.lineage.verificationStatus,'SYNTHETIC');assert.equal(run.consumer.snapshot.fiveA.transitions.A2_TO_A3.changeVsLast.value,null);}});
test('panel and renderer share snapshot id and rate through provider',()=>{for(const [name,e] of Object.entries(evidence)){assert.equal(e.execution.metadata.snapshotId,e.snapshotId);assert.equal(e.panel.conversionRate,e.canonical.rate.value);assert.equal(e.execution.metadata.sourceType,'MOCK');assert.equal(e.execution.renderer.binding.flowStrength,cases[name].visual.fiveA.transitions.A2_TO_A3.flowStrength);}});
test('LOW HIGH direction agrees with Mapping, Binding and real aAlpha',()=>{assert.ok(evidence.low.visual.flowStrength<evidence.high.visual.flowStrength);const lo=evidence.low.execution.renderer,hi=evidence.high.execution.renderer;assert.ok(hi.alphas.some((v,i)=>v>lo.alphas[i]));for(let i=0;i<hi.alphas.length;i++)assert.ok(hi.alphas[i]>=lo.alphas[i]);});
test('all four real GPU alpha arrays equal original alpha times mapped strength',()=>{for(const e of Object.values(evidence)){const r=e.execution.renderer;for(let i=0;i<r.alphas.length;i++)assert.ok(Math.abs(r.alphas[i]-r.baseAlphas[i]*r.binding.flowStrength)<1e-7);}});
test('other three transitions and both Opportunity entrance segments unchanged',()=>{for(const run of Object.values(cases)){adapter.apply(run.plan);tick();const states=scene.readTransitionRendererStates();for(const id of Object.keys(original).filter(id=>id!=='A2_TO_A3'))assert.deepEqual(states[id],original[id]);}});
test('A1-A5 real scales and energies unchanged',()=>{for(const run of Object.values(cases)){adapter.apply(run.plan);tick();assert.deepEqual(stageAdapter.getReport().renderer,stageOriginal);}});
test('path positions, shader, geometry, particle count and batch unchanged',()=>{assert.deepEqual([...flow.geometry.attributes.position.array],positions);assert.deepEqual({geometry:flow.geometry.uuid,material:flow.material.uuid,count:flow.geometry.attributes.position.count,vertex:flow.material.vertexShader,fragment:flow.material.fragmentShader},resource);});
test('HIGH LOW repeated 100 times and idempotent reapply without accumulated multiplication',()=>{for(let i=0;i<100;i++){adapter.apply(cases.high.plan);adapter.apply(cases.low.plan);assert.deepEqual(adapter.getReport().renderer,evidence.low.execution.renderer);adapter.apply(cases.low.plan);assert.deepEqual(adapter.getReport().renderer,evidence.low.execution.renderer);}});
test('release capture stable retain positions at equal clock and progress',()=>{for(const p of [0.3,0.6,1]){adapter.apply(cases.low.plan);tick(12.25,p);const before=[...flow.geometry.attributes.position.array];adapter.apply(cases.high.plan);tick(12.25,p);assert.deepEqual([...flow.geometry.attributes.position.array],before);}});
test('missing stays null with safe fallback and traceable missing path',()=>{const e=evidence.partial;assert.equal(e.canonical.rate.value,null);assert.equal(e.canonical.out.value,null);assert.equal(e.execution.renderer.binding.flowStrength,0.1);assert.equal(e.execution.metadata.entry.missing,true);assert.ok(e.execution.metadata.sourceMissingPaths.includes('fiveA.transitions.A2_TO_A3.flowStrength'));});
test('missing cohort exits remain missing in Derived and Panel, never A3 population',()=>{assert.equal(cases.partial.consumer.derivedMetrics.transitions.A2_TO_A3.out,null);assert.equal(evidence.partial.panel.outPopulation,null);assert.equal(evidence.partial.panel.outPopulationLabel,'未提供');});
test('missing cohort entrants remain missing despite known A2 population',()=>{const snapshot=structuredClone(createFiveAFlowDemoSnapshot('partial'));snapshot.fiveA.transitions.A2_TO_A3.in.value=null;const c=createV2ConsumerProvider({fiveASnapshot:snapshot}).getFiveA();assert.equal(c.derivedMetrics.transitions.A2_TO_A3.in,null);assert.equal(c.snapshot.fiveA.stages.A2.population.value,6100);});
test('invalid values and wrong targets reject without partial mutation',()=>{for(const value of [NaN,Infinity,-1,2]){const plan=structuredClone(cases.high.plan);plan.fiveA.transitions.find(e=>e.transitionId==='A2_TO_A3'&&e.channel.endsWith('FLOW_STRENGTH')).value=value;const before=adapter.getReport();assert.throws(()=>adapter.apply(plan));assert.deepEqual(adapter.getReport(),before);}const plan=structuredClone(cases.high.plan);plan.fiveA.transitions.find(e=>e.transitionId==='A2_TO_A3'&&e.channel.endsWith('FLOW_STRENGTH')).targetId='A3_TO_A4';assert.throws(()=>adapter.apply(plan));});
test('duplicate or missing channel fails atomically',()=>{for(const duplicate of [false,true]){const plan=structuredClone(cases.high.plan);const index=plan.fiveA.transitions.findIndex(e=>e.transitionId==='A2_TO_A3'&&e.channel.endsWith('FLOW_STRENGTH'));if(duplicate)plan.fiveA.transitions.push(structuredClone(plan.fiveA.transitions[index]));else plan.fiveA.transitions.splice(index,1);const before=adapter.getReport();assert.throws(()=>adapter.apply(plan));assert.deepEqual(adapter.getReport(),before);}});
test('write failure rollback preserves runtime and metadata',()=>{let value={flowStrength:1},fail=true;const a=createFiveAFlowRendererAdapter(()=>({transitionId:'A2_TO_A3',read:()=>({binding:{...value}}),write:v=>{value={...v};if(fail){fail=false;throw Error('simulated');}}}));assert.throws(()=>a.apply(cases.low.plan));assert.deepEqual(value,{flowStrength:1});assert.equal(a.getReport().metadata,null);a.dispose();});
test('channel reorder within canonical transition order binds by ID; speed is never written',()=>{const plan=structuredClone(cases.baseline.plan);for(let i=0;i<plan.fiveA.transitions.length;i+=2)[plan.fiveA.transitions[i],plan.fiveA.transitions[i+1]]=[plan.fiveA.transitions[i+1],plan.fiveA.transitions[i]];adapter.apply(plan);assert.deepEqual(Object.keys(adapter.getReport().renderer.binding),['flowStrength']);assert.equal(adapter.getReport().renderer.binding.flowStrength,evidence.baseline.visual.flowStrength);});
test('panel temporary presentation leaves binding unchanged',()=>{const before=adapter.getReport();scene.setPanelPresentationOpen(true);scene.setPanelPresentationOpen(false);assert.deepEqual(adapter.getReport(),before);});
test('fixture deterministic and default/production URLs inert',()=>{assert.deepEqual(createFiveAFlowDemoSnapshot('low'),createFiveAFlowDemoSnapshot('low'));assert.equal(resolveFiveAFlowDemo('',true),null);assert.equal(resolveFiveAFlowDemo('?v2FiveAFlowState=high',false),null);assert.throws(()=>createFiveAFlowDemoSnapshot('other'));assert.throws(()=>resolveFiveAFlowDemo('?v2FiveAFlowState=high&v2FiveAFlowFrame=9',true));});
test('real target rejects flowSpeed and out of guardrail writes',()=>{assert.throws(()=>scene.resolveTransitionRendererTarget('A2_TO_A3').write({flowSpeed:1}));assert.throws(()=>scene.resolveTransitionRendererTarget('A2_TO_A3').write({flowStrength:Infinity}));});
test('disposal restores art, invalidates target and scene reopens fresh',()=>{const target=scene.resolveTransitionRendererTarget('A2_TO_A3');adapter.dispose();adapter.dispose();assert.equal(target.read().binding.flowStrength,1);assert.throws(()=>adapter.apply(cases.low.plan));stageAdapter.dispose();scene.dispose();assert.throws(()=>target.read());const fresh=createFiveAScene();assert.equal(fresh.resolveTransitionRendererTarget('A2_TO_A3').read().binding.flowStrength,1);fresh.dispose();});
test('runtime uses one provider and existing loop; adapter has no visual business calculation',()=>{const engine=readFileSync(new URL('../../engine/index.js',import.meta.url),'utf8');assert.equal((engine.match(/createV2ConsumerProvider\(/g)||[]).length,1);assert.ok(engine.indexOf('flowAdapter?.dispose()')<engine.indexOf('sceneManager.dispose()'));const code=readFileSync(new URL('./fiveAFlowRendererAdapter.js',import.meta.url),'utf8');assert.doesNotMatch(code,/requestAnimationFrame|normalizeDataPoint|deriveFiveAMetrics|document\./);});
const summary={passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results};console.log(JSON.stringify(summary,null,2));
if(process.argv.includes('--report')){const dir=new URL('../../../art/v2-3b-a2-a3-flow/',import.meta.url);mkdirSync(dir,{recursive:true});writeFileSync(new URL('flow-values.json',dir),JSON.stringify({summary,evidence},null,2));}
if(summary.failed)process.exitCode=1;
